<?php 
header("Content-type: application/vnd.ms-word");
header("Content-Disposition: attachment;Filename=customer_report.doc");
include_once("classes/Database.php");
$crud = new Database();
$id = $_GET['id'];
$query = 'SELECT * FROM catepillar_report WHERE id='.$id;
$result = $crud->getSingleRow($query);
$q = 'SELECT full_name FROM users WHERE id='.$result['checked_by'];
$rs = $crud->getSingleRow($q);
$q2 = 'SELECT full_name FROM users WHERE id='.$result['approved_by'];
$rs2 = $crud->getSingleRow($q2);
$data = json_decode($result['data'],TRUE);
$q3  = 'SELECT full_name FROM users WHERE id='.$result['verified_by'];
$rs3 = $crud->getSingleRow($q3);
echo "<html>";
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=Windows-1252\">";
echo "<body>";
echo "<style>table{ border-right : 1px solid #000;width:100%;font-size:12px;font-family: sans-serif;}td{ border-top : 1px solid #000; border-left:1px solid #000;}</style>";
echo "<table style='border-bottom:1px solid #000;' class='table display nowrap table-bordered'>";
echo "<tr><td colspan='12' style='margin-left:140px;'><img src='".$fol."/image/ve_logo.png' alt='Beoro Admin'></td></tr>";
echo "<tr><td colspan='5'><img src='".$fol."/img/caterpillar.jpg'></td>
<td colspan='2' style='font-size:14px; border-left:0px;'></td>
<td colspan='5' style='border-left:0px;'>Format No:- AP04:460:10CAT</td></tr>";
echo "<tr><td colspan='12' style='background-color:#ccc;text-align: center;'>METALLURGICAL TEST REPORT</td></tr>";
echo "<tr><td colspan='12'>Report No:- ".$result['report_no']."</td></tr>";
echo "<tr><td colspan='3'>Customer</td><td colspan='3'>".$result['customer']."</td><td colspan='3'>Date</td><td colspan='3'>".$result['date']."</td></tr>";
echo "<tr><td colspan='3'>Cust Part Id</td><td colspan='3'>".$result['control_plan_id']."</td><td colspan='3'>Batch Code</td><td colspan='3'>".$result['batch_code']."</td></tr>";
echo "<tr><td colspan='3'>EECD Part No.</td><td colspan='3'>".$result['part_no']."</td><td colspan='3'>Qty</td><td colspan='3'>".$result['qty']."</td></tr>";
echo "<tr><td colspan='3'>Part Name</td><td colspan='3'>".$result['part_name']."</td><td colspan='3'>Material</td><td colspan='3'>".$result['grade']."</td></tr>";
echo "<tr><td colspan='3'>Steel Mill</td><td colspan='3'>".$result['steel_mill']."</td><td colspan='3'>Heat No.</td><td colspan='3'>".$result['heat_no']."</td></tr>";
echo "<tr style='background-color:#ccc;text-align: center;'><td colspan='1'>S.No</td><td colspan='2'>Parameters</td><td colspan='2'>Location</td><td colspan='2'>Specification</td><td colspan='2'>Observation</td><td colspan='1'></td><td colspan='1'></td><td colspan='1'>Remark</td></tr>";
echo "<tr><td colspan='1' rowspan='3'>1.</td><td colspan='2' rowspan='3'>Effective Case Depth in mm</td><td colspan='2'>".$data['metallurgical_test_case_depth_pcd_location']."</td><td colspan='2'>".$data['eff_after_grinding_requirement1']."</td><td colspan='2'>".$data['remark_observe1']."</td><td colspan='1'>".$data['metallurgical_test_case_depth_pcd_observation1']."</td><td colspan='1'>".$data['metallurgical_test_case_depth_pcd_observation2']."</td><td colspan='1'>".$data['remark_ag']."</td></tr>";
echo "<tr><td colspan='2'>".$data['metallurgical_test_case_depth_location']."</td><td colspan='2'>".$data['metallurgical_test_case_depth_requirement']."</td><td colspan='2'>".$data['metallurgical_test_case_depth_observation']."</td><td colspan='1'>".$data['metallurgical_test_case_depth_observation1']."</td><td colspan='1'>".$data['metallurgical_test_case_depth_observation2']."</td><td colspan='1'>".$data['remark4']."</td></tr>";
echo "<tr><td colspan='2'>".$data['eff_case_depth_location']."</td><td colspan='2'>".$data['eff_case_depth_requirement']."</td><td colspan='2'>".$data['eff_case_depth_observation']."</td><td colspan='1'>".$data['eff_case_depth_observation1']."</td><td colspan='1'>".$data['eff_case_depth_observation2']."</td><td colspan='1'>".$data['eff_case_depth_observation_remark']."</td></tr>";
echo "<tr><td colspan='1'>2.</td><td colspan='2'>Hardness in HRC</td><td colspan='2'>".$data['metallurgical_test_surface_hard2_location']."</td><td colspan='2'>".$data['metallurgical_test_surface_hard2_requirement']." ".$data['surface_hardnessloc1_value']."</td><td colspan='2'>".$data['metallurgical_test_surface_hard2_observation']."</td><td colspan='1'>".$data['metallurgical_test_surface_hard2_observation1']."</td><td colspan='1'>".$data['metallurgical_test_surface_hard2_observation2']."</td><td colspan='1'>".$data['remark2']."</td></tr>";
echo "<tr><td colspan='1' rowspan='3'>3.</td><td colspan='2' rowspan='3'>Core Hardness in HRC</td><td colspan='2'>".$data['metallurgical_test_core_hardness_pcd_location']."</td><td colspan='2'>".$data['metallurgical_test_core_hardness_pcd_requirement']."</td><td colspan='2'>".$data['metallurgical_test_core_hardness_pcd_observation']."</td><td colspan='1'>".$data['metallurgical_test_core_hardness_pcd_observation1']."</td><td colspan='1'>".$data['metallurgical_test_core_hardness_pcd_observation2']."</td><td colspan='1'>".$data['remark7']."</td></tr>";
echo "<tr><td colspan='2'>".$data['metallurgical_test_core_hardness_rcd_location']."</td><td colspan='2'>".$data['metallurgical_test_core_hardness_rcd_requirement']."</td><td colspan='2'>".$data['metallurgical_test_core_hardness_rcd_observation']."</td><td colspan='1'>".$data['metallurgical_test_core_hardness_rcd_observation1']."</td><td colspan='1'>".$data['metallurgical_test_core_hardness_rcd_observation2']."</td><td colspan='1'>".$data['remark8']."</td></tr>";
echo "<tr><td colspan='2'>".$data['core_hardness_location']."</td><td colspan='2'>".$data['core_hardness_requirement']."</td><td colspan='2'>".$data['core_hardness_observation']."</td><td colspan='1'>".$data['core_hardness_observation1']."</td><td colspan='1'>".$data['core_hardness_observation2']."</td><td colspan='1'>".$data['core_hardness_remark']."</td></tr>";
echo "<tr><td colspan='1'>4.</td><td colspan='2'>Surface Hardness after final grinding in HRC</td><td colspan='2'>".$data['surface_hardness_location_after_grind']."</td><td colspan='2'>".$data['surface_hardness_requirement_after_grind']."</td><td colspan='2'>".$data['remark_observe3']."</td><td colspan='1'>".$data['remark_observe31']."</td><td colspan='1'>".$data['remark_observe32']."</td><td colspan='1'>".$data['remark_ag3']."</td></tr>";
echo "<tr><td colspan='1'>5.</td><td colspan='2'>Surface Hardness in HRC</td><td colspan='2'>".$data['metallurgical_test_surface_hard1_location']."</td><td colspan='2'>".$data['metallurgical_test_surface_hard1_requirement']."".$data['surface_hardnessloc_value']."</td><td colspan='2'>".$data['metallurgical_test_surface_hard1_observation']."</td><td colspan='1'>".$data['metallurgical_test_surface_hard1_observation1']."</td><td colspan='1'>".$data['metallurgical_test_surface_hard1_observation2']."</td><td colspan='1'>".$data['remark1']."</td></tr>";
echo "<tr><td rowspan='2' colspan='1'>6.</td><td rowspan='2' colspan='2'>Surface Bainite</td><td colspan='2'>".$data['metallurgical_test_nmtp_surface_pcd_location']."</td><td colspan='2'>".$data['metallurgical_test_nmtp_surface_pcd_requirement']."</td><td colspan='2'>".$data['metallurgical_test_nmtp_surface_pcd_observation']."</td><td colspan='1'>".$data['metallurgical_test_nmtp_surface_pcd_observation1']."</td><td colspan='1'>".$data['metallurgical_test_nmtp_surface_pcd_observation2']."</td><td colspan='1'>".$data['remark_nmtp']."</td></tr>";
echo "<tr><td colspan='2'>".$data['metallurgical_test_nmtp_surface_rcd_location']."</td><td colspan='2'>".$data['metallurgical_test_nmtp_surface_rcd_requirement']."</td><td colspan='2'>".$data['metallurgical_test_nmtp_surface_rcd_observation']."</td><td colspan='1'>".$data['metallurgical_test_nmtp_surface_rcd_observation1']."</td><td colspan='1'>".$data['metallurgical_test_nmtp_surface_rcd_observation2']."</td><td colspan='1'>".$data['remark_nmtp2']."</td></tr>";
echo "<tr><td rowspan='2' colspan='1'>7.</td><td rowspan='2' colspan='2'>Sub Surface Bainite</td><td colspan='2'>".$data['metallurgical_test_itp_sub_surface_pcd_location']."</td><td colspan='2'>".$data['metallurgical_test_itp_sub_surface_pcd_requirement']."</td><td colspan='2'>".$data['metallurgical_test_itp_sub_surface_pcd_observation']."</td><td colspan='1'>".$data['metallurgical_test_itp_sub_surface_pcd_observation1']."</td><td colspan='1'>".$data['metallurgical_test_itp_sub_surface_pcd_observation2']."</td><td colspan='1'>".$data['remark_itp']."</td></tr>";
echo "<tr><td colspan='2'>".$data['metallurgical_test_itp_sub_surface_rcd_location']."</td><td colspan='2'>".$data['metallurgical_test_itp_sub_surface_rcd_requirement']."</td><td colspan='2'>".$data['metallurgical_test_itp_sub_surface_rcd_observation']."</td><td colspan='1'>".$data['metallurgical_test_itp_sub_surface_rcd_observation1']."</td><td colspan='1'>".$data['metallurgical_test_itp_sub_surface_rcd_observation2']."</td><td colspan='1'>".$data['remark_itp2']."</td></tr>";
echo "<tr><td colspan='1'>8.</td><td colspan='2'>Grain Boundary Oxidation</td><td colspan='2'>".$data['metallurgical_test_gbo_igo_pcd_location']."</td><td colspan='2'>".$data['metallurgical_test_gbo_igo_pcd_requirement']."</td><td colspan='2'>".$data['metallurgical_test_gbo_igo_pcd_observation']."</td><td colspan='1'>".$data['metallurgical_test_gbo_igo_pcd_observation1']."</td><td colspan='1'>".$data['metallurgical_test_gbo_igo_pcd_observation2']."</td><td colspan='1'>".$data['remark_gbo']."</td></tr>";
echo "<tr><td rowspan='4' colspan='1'>9.</td><td colspan='2'>Dark etched Microstructure Retained Austenite</td><td colspan='2'>".$data['metallurgical_test_micro_case_location']."</td><td colspan='2'>".$data['metallurgical_test_micro_case_requirement']."</td><td colspan='2'>".$data['metallurgical_test_micro_case_observation']."</td><td colspan='1'>".$data['d1_observation1']."</td><td colspan='1'>".$data['d1_observation2']."</td><td colspan='1'>".$data['d1_remark']."</td></tr>";
echo "<tr><td colspan='2'>Carbides</td><td colspan='2'>".$data['dc_location']."</td><td colspan='2'>".$data['dc_requirement']."</td><td colspan='2'>".$data['dc_observation']."</td><td colspan='1'>".$data['dc_observation1']."</td><td colspan='1'>".$data['dc_observation2']."</td><td colspan='1'>".$data['dc_remark']."</td></tr>";
echo "<tr><td colspan='2'>Decarb</td><td colspan='2'>".$data['decarb_location']."</td><td colspan='2'>".$data['decarb_requirement']."</td><td colspan='2'>".$data['decarb_observation']."</td><td colspan='1'>".$data['decarb_observation1']."</td><td colspan='1'>".$data['decarb_observation2']."</td><td colspan='1'>".$data['decarb_remark']."</td></tr>";
echo "<tr><td colspan='2'>Core Ferrite</td><td colspan='2'>".$data['ferrite_location']."</td><td colspan='2'>".$data['ferrite_requirement']."</td><td colspan='2'>".$data['ferrite_observation']."</td><td colspan='1'>".$data['ferrite_observation1']."</td><td colspan='1'>".$data['ferrite_observation2']."</td><td colspan='1'>".$data['ferrite_remark']."</td></tr>";
echo "<tr><td colspan='2' style='height: 50px;'>Remark :</td><td colspan='10' style='height: 50px;'>".$result['remark']."</td></tr>";
echo "</table>";
echo "<br pagebreak='true' />";
echo "<table style='border-bottom:1px solid #000;'>";
echo "<tr><td colspan='12' style='text-align: center;background-color:#ccc;'>Micro Photographs Magnification : 500 X</td></tr>";
echo "<tr><td colspan='6'style='height: 250px;'></td><td colspan='6' style='height: 250px;'></td></tr>";
echo "<tr><td colspan='6'>Surface Bainite Loc-X</td><td colspan='6'>Surface Bainite Loc-C</td></tr>";
echo "<tr><td colspan='6' style='height: 250px;'></td><td colspan='6' style='height: 250px;'></td></tr>";
echo "<tr><td colspan='6'>Case Microstructure Loc-X</td><td colspan='6'>Core Microstructue Loc-D</td></tr>";
echo "<tr><td colspan='2'>Checked by :- </td><td colspan='2'>".$rs['full_name']."</td><td colspan='2'>Prepared By:-</td><td colspan='2'>".$rs3['full_name']."</td><td colspan='2'>Approved by :- </td><td colspan='2'> ".$rs2['full_name']."</td></tr>";

echo "</table>";
echo "</body>";
echo "</html>";